### ISSUE TITLE
SimpleFin to Maybe integration fails to persist retrieved accounts between sessions

### ISSUE THREAD

**Issue by danshaw** [steveredden/simplefin_to_maybe#27]
Trying to set this up and could use some help. I got the container up and running. I am able to enter in the settings for SimpleFin and those are retrieved just fine. I am able to set a schedule just fine. Problem I am having is that when I enter the maybe settings to retrieve the accounts, it finds the accounts, but those settings are not persisting. If I reload or go to another page, they disappear. I drilled into the database through docker and found that the settings are persisting, just not the found accounts. 

Below are my compose files and some other details to help provide context. 

## Sanitized SimpleFin to Maybe Docker Compose

```yaml
version: '3.8'

services:
  web:
    container_name: simplefin_to_maybe
    image: ghcr.io/steveredden/simplefin_to_maybe:latest
    volumes:
      - /volume1/docker/maybe/simplefin/app-storage:/app/storage
    ports:
      - "3490:3000"
    networks:
      - shared_network
    restart: unless-stopped
    environment:
      SECRET_KEY_BASE: "****"
      DB_HOST: "s2m-db"
      DB_PORT: 5432
      POSTGRES_USER: "simplefin_to_maybe"
      POSTGRES_PASSWORD: "****"
      POSTGRES_DB: "simplefin_to_maybe"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      TZ: "America/New_York"
    depends_on:
      s2m-db:
        condition: service_healthy

  s2m-db:
    container_name: simplefin_to_maybe-db
    image: postgres:16
    restart: unless-stopped
    networks:
      - shared_network
    volumes:
      - /volume1/docker/maybe/simplefin/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "simplefin_to_maybe"
      POSTGRES_PASSWORD: "****"
      POSTGRES_DB: "simplefin_to_maybe"
      TZ: "America/New_York"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  shared_network:
    external: true
```

## Sanitized Maybe Finance Docker Compose

```yaml
services:
  web:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - /volume1/docker/maybe/app-storage:/rails/storage
    ports:
      - "3485:3000"
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://postgres:****@db:5432/maybe_production"
      REDIS_URL: "redis://:****@redis:6379/1"
      OPENAI_ACCESS_TOKEN: "****"
      SECRET_KEY_BASE: "****"
      SELF_HOSTED: "true"
      RAILS_ENV: "production"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - maybe_network
      - shared_network
    command: bash -c "rm -f /rails/tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

  worker:
    image: ghcr.io/maybe-finance/maybe:latest
    command: bash -c "bundle exec sidekiq"
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://postgres:****@db:5432/maybe_production"
      REDIS_URL: "redis://:****@redis:6379/1"
      PLAID_CLIENT_ID: "****"
      PLAID_SECRET: "****"
      PLAID_ENV: "development"
      OPENAI_ACCESS_TOKEN: "****"
      DISABLE_REGISTRATION: "true"
      SECRET_KEY_BASE: "****"
      SELF_HOSTED: "true"
      RAILS_ENV: "production"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - maybe_network
      - shared_network

  db:
    image: postgres:16
    container_name: maybe-finance-database
    restart: unless-stopped
    volumes:
      - /volume1/docker/maybe/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d maybe_production" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "****"
      POSTGRES_DB: maybe_production
    networks:
      - maybe_network
      - shared_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ****
    volumes:
      - /volume1/docker/maybe/redis-data:/data
    networks:
      - maybe_network
      - shared_network

networks:
  maybe_network:
    driver: bridge
  shared_network:
    external: true
```

## Issue Summary

**Issue**: SimpleFin to Maybe integration fails to persist retrieved accounts between sessions

**Environment**:
- SimpleFin to Maybe version: latest (from ghcr.io/steveredden/simplefin_to_maybe)
- Maybe Finance version: latest (from ghcr.io/maybe-finance/maybe)
- PostgreSQL version: 16
- Redis version: 7-alpine
- Platform: Docker on Synology NAS

**Configuration**:
- Both applications have persistent volume storage configured
- Both applications are connected via a shared external network
- The SimpleFin to Maybe service is configured to connect to the Maybe Finance database

**Problem**:
- Connection test shows successful database connectivity
- Settings are saved correctly (all updates return 200 OK)
- Account retrieval appears to work initially
- However, retrieved accounts don't persist after reloading the application

**Technical Details**:
- The applications communicate via a shared Docker network (shared_network)
- Both services have their own PostgreSQL databases with persistent storage
- Maybe Finance has proper health checks configured for its database
- SimpleFin to Maybe also has health checks configured for its database

**Additional Information**:
- The data persistence issue occurs after retrieving accounts from the Maybe database
- The issue persists across container restarts
- Both applications are using proper volume mounts for data persistence

![Image](https://github.com/user-attachments/assets/b1395a19-9ad4-4447-abca-b02b2232e4bc)

If I hit reload, this happens:

![Image](https://github.com/user-attachments/assets/7fe23f81-0640-4fdb-8e3a-cb9990b45e43)
